version: "3.1"
services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./ini:/usr/local/etc/php
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: phptests
      MYSQL_DATABASE: phptests
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"


